name: Update Deadline

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python
        run: |
          python fetch.py

      - name: Upload products
        uses: actions/upload-artifact@v4
        with:
          name: products
          path: products.json
